version: '3'

services:
  django:
    build:
      context: ./django
    env_file:
      - .env
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 127.0.0.1:8000:8000
